export const schoolData = [
  {
    sch_name: "Pave Academy Charter School",
    prop_as: 3.6,
    prop_bl: 39.3,
    prop_hi: 55.4,
    prop_or: 0,
    prop_wh: 1.8,
  },
  {
    sch_name: "Summit Academy Charter School",
    prop_as: 0,
    prop_bl: 21.6,
    prop_hi: 75.7,
    prop_or: 0,
    prop_wh: 2.7,
  },
  {
    sch_name: "Sunset Park Prep",
    prop_as: 20.9,
    prop_bl: 1.1,
    prop_hi: 75.4,
    prop_or: 0,
    prop_wh: 2.7,
  },
  {
    sch_name: "Is 136 Charles O. Dewey",
    prop_as: 8.7,
    prop_bl: 1.1,
    prop_hi: 84.8,
    prop_or: 1.1,
    prop_wh: 4.3,
  },
  {
    sch_name: "Jhs 88 Peter Rouget",
    prop_as: 20.7,
    prop_bl: 13.5,
    prop_hi: 55,
    prop_or: 1.8,
    prop_wh: 9,
  },
  {
    sch_name: "Brooklyn Urban Garden Charter School",
    prop_as: 1,
    prop_bl: 38.4,
    prop_hi: 34.3,
    prop_or: 5.1,
    prop_wh: 21.2,
  },
  {
    sch_name: "Brooklyn Collaborative Studies",
    prop_as: 3.5,
    prop_bl: 23.5,
    prop_hi: 37.4,
    prop_or: 6.1,
    prop_wh: 29.6,
  },
  {
    sch_name: "Park Slope Collegiate",
    prop_as: 8.4,
    prop_bl: 26.3,
    prop_hi: 33.7,
    prop_or: 1.1,
    prop_wh: 30.5,
  },
  {
    sch_name: "Hellenic Classical Charter School",
    prop_as: 2,
    prop_bl: 18,
    prop_hi: 38,
    prop_or: 10,
    prop_wh: 32,
  },
  {
    sch_name: "Brooklyn Prospect Charter School-Csd 15",
    prop_as: 8.2,
    prop_bl: 13.6,
    prop_hi: 36.4,
    prop_or: 5.5,
    prop_wh: 36.4,
  },
  {
    sch_name: "MS 839",
    prop_as: 9.4,
    prop_bl: 10.2,
    prop_hi: 29.7,
    prop_or: 5.5,
    prop_wh: 45.3,
  },
  {
    sch_name: "MS 51 William Alexander",
    prop_as: 19.4,
    prop_bl: 6.2,
    prop_hi: 22.5,
    prop_or: 4.9,
    prop_wh: 47,
  },
  {
    sch_name: "Math and Science Exploratory School (the)",
    prop_as: 10.9,
    prop_bl: 15.2,
    prop_hi: 22.8,
    prop_or: 2.7,
    prop_wh: 48.4,
  },
  {
    sch_name: "Boerum Hill School for International Studies (the)",
    prop_as: 2.9,
    prop_bl: 18.8,
    prop_hi: 19.4,
    prop_or: 8.2,
    prop_wh: 50.6,
  },
  {
    sch_name: "MS 442 Carroll Gardens School for Innovation",
    prop_as: 12.8,
    prop_bl: 7.1,
    prop_hi: 22,
    prop_or: 6.4,
    prop_wh: 51.8,
  },
  {
    sch_name: "New Voices School of Academic and Creative Arts",
    prop_as: 9.3,
    prop_bl: 9.3,
    prop_hi: 20.5,
    prop_or: 4.9,
    prop_wh: 56.1,
  },
];
