services:
    nextjs:
      build: 
        context: ./frontend
        dockerfile: Dockerfile.prod
      environment:
        - NEXT_PUBLIC_MAPBOX_TOKEN=${MAPBOX_TOKEN}
        - NEXT_PUBLIC_BACKEND_URL=https://integrateusa.org
    nginx: 
        restart: unless-stopped
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            # - static_volume:/app/backend/server/django_static
            - ./nginx/Production:/etc/nginx/conf.d
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
        depends_on: 
            - django
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"       
    django:
      build:
        context: .
        dockerfile: Dockerfile.prod
      environment:
        - SECRET_KEY='${SECRET_KEY}'
        - POSTGRES_NAME=${POSTGRES_NAME}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_HOST=${POSTGRES_HOST}
      entrypoint: ./wsgi-entrypoint.sh
      # volumes: 
      #   - static_volume:app/integrateusa/django_static
      expose:
      - 8000:8000      

volumes:
    static_volume: {}