version: '3'
services:
  nextjs:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - SECRET_KEY=
      - POSTGRES_NAME=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=
    entrypoint: ./wsgi-entrypoint.sh
    # volumes: 
    #   - static_volume:app/integrateusa/django_static
    expose:
      - 8000:8000
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80