# syntax=docker/dockerfile:1

FROM python:3
WORKDIR /app
ADD ./requirements.txt /app/backend/
RUN pip install --upgrade pip
RUN pip install gunicorn
COPY requirements.txt /app/
RUN pip install -r requirements.txt
COPY . /app/
