export {
  primaryColor,
  asianColor,
  blackColor,
  hispanicColor,
  whiteColor,
  otherColor,
  selectedAreaColor,
  unselectedAreaColor,
  districtBoundaryURL,
  countyBoundaryURL,
  stateBoundaryURL,
  selectedLineColor,
  unselectedLineColor,
  defaultMapSchoolColor,
} from "./constants";
