# Generated by Django 4.1.1 on 2022-09-13 18:59

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countynames',
            name='vector_col',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='countynames',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_col'], name='county_name_vector__964edf_gin'),
        ),
    ]
