# Generated by Django 4.1.1 on 2022-09-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_countynames_vector_col_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='countynames',
            name='county_name_vector__964edf_gin',
        ),
    ]
