# Generated by Django 4.1.1 on 2022-09-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_countynames_county_name_vector__964edf_gin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countynames',
            name='vector_col',
        ),
        migrations.AlterField(
            model_name='schools',
            name='county_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schools',
            name='dist_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schools',
            name='grade',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='schools',
            name='state_abb',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='schools',
            name='year',
            field=models.IntegerField(),
        ),
    ]
