# Generated by Django 4.1.1 on 2022-09-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_countynames_vector_col_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schools',
            index=models.Index(fields=['year'], name='year_idx'),
        ),
        migrations.AddIndex(
            model_name='schools',
            index=models.Index(fields=['grade'], name='grade_idx'),
        ),
        migrations.AddIndex(
            model_name='schools',
            index=models.Index(fields=['dist_id'], name='dist_idx'),
        ),
        migrations.AddIndex(
            model_name='schools',
            index=models.Index(fields=['county_id'], name='county_idx'),
        ),
        migrations.AddIndex(
            model_name='schools',
            index=models.Index(fields=['state_abb'], name='state_idx'),
        ),
    ]
