# Generated by Django 4.1.1 on 2022-09-13 20:45

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_school_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='countynames',
            name='vector_col',
            field=django.contrib.postgres.search.SearchVectorField(default=''),
        ),
    ]
