# Generated by Django 4.1.1 on 2022-09-13 20:46

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_countynames_vector_col'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='countynames',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_col'], name='county_name_idx'),
        ),
    ]
