# Generated by Django 4.1.1 on 2022-09-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_countynames_county_name_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='countynames',
            name='county_name_idx',
        ),
    ]
