# Generated by Django 4.1.1 on 2022-09-14 19:17

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_countynames_county_name_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='countynames',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_col'], name='county_name_idx'),
        ),
    ]
