# Generated by Django 4.1.2 on 2022-10-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_countynames_county_name_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyTrends',
            fields=[
                ('county_key', models.TextField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('county_id', models.IntegerField()),
                ('county_name', models.TextField()),
                ('asian', models.IntegerField()),
                ('black', models.IntegerField()),
                ('hispanic', models.IntegerField()),
                ('other', models.IntegerField()),
                ('white', models.IntegerField()),
            ],
            options={
                'db_table': 'county_trends',
            },
        ),
        migrations.CreateModel(
            name='DistrictTrends',
            fields=[
                ('dist_key', models.TextField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('dist_id', models.IntegerField()),
                ('dist_name', models.TextField()),
                ('asian', models.IntegerField()),
                ('black', models.IntegerField()),
                ('hispanic', models.IntegerField()),
                ('other', models.IntegerField()),
                ('white', models.IntegerField()),
            ],
            options={
                'db_table': 'dist_trends',
            },
        ),
        migrations.CreateModel(
            name='MapSchools',
            fields=[
                ('map_data', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'map_schools',
            },
        ),
        migrations.CreateModel(
            name='StateTrends',
            fields=[
                ('state_key', models.TextField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('state_abb', models.CharField(max_length=2)),
                ('asian', models.IntegerField()),
                ('black', models.IntegerField()),
                ('hispanic', models.IntegerField()),
                ('other', models.IntegerField()),
                ('white', models.IntegerField()),
            ],
            options={
                'db_table': 'state_trends',
            },
        ),
        migrations.AddField(
            model_name='schools',
            name='prop_as',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='schools',
            name='prop_bl',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='schools',
            name='prop_hi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='schools',
            name='prop_or',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='schools',
            name='prop_wh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='schools',
            name='sch_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='schools',
            name='grade',
            field=models.TextField(),
        ),
    ]
