import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Integrate USA Testing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mg_logo_cropped.png" />
      </Head>

      <main className={styles.main}>
        
        <p>Testing</p>
    
      </main> 
    </div>
  )
}
