name: Push-to-EC2
on:
  push:
    branches:
      - PRODUCTION
jobs:
  deploy:
    name: Deploy to EC2 on PRODUCTION branch push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
      - name: Create env files
        run: |
          touch .env
          echo SECRET_KEY=${{secrets.SECRET_KEY}} >> .env
          echo POSTGRES_NAME=${{secrets.POSTGRES_NAME}} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER}} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD}} >> .env
          echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST}} >> .env
          cat .env
          cd frontend
          touch .env
          echo NEXT_PUBLIC_MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN}} >> .env
          cat .env
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            sudo docker-compose -f docker-compose-production.yml down
            sudo docker system prune -af
            sudo docker-compose -f docker-compose-production.yml build
            sudo docker-compose -f docker-compose-production.yml up --detach
